// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azxsyhnmpatffocueiia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6eHN5aG5tcGF0ZmZvY3VlaWlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MTYzMTEsImV4cCI6MjA2MzQ5MjMxMX0.YTU7ojQJ3Tnzf7tx7aEJ8yyYB7xG-gX_80VUloL38ec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);